// US Funnel Configurations
// These define all funnels for US jurisdictions

import { 
  FunnelConfig, 
  LegalCategory, 
  FunnelStep,
  generateFunnelId,
  generateSlug,
  US_STATE_NAMES,
  LEGAL_AREA_NAMES
} from './types';

// Default steps - NEW CONTINUOUS FLOW
// triage → evidence → results (merit+pathway+forms teaser FREE) → paywall → generate → next_steps
const STANDARD_STEPS: FunnelStep[] = [
  'triage',
  'evidence',
  'results',      // Shows merit score, pathway teaser, form names (FREE)
  'paywall',      // Payment gate
  'generate',
  'next_steps'
];

// Steps with payment (same as standard now)
const PAID_STEPS: FunnelStep[] = [
  'triage',
  'evidence',
  'results',
  'paywall',
  'generate',
  'next_steps'
];

// All 50 states + DC enabled
export const ENABLED_STATES = [
  'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL',
  'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME',
  'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH',
  'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI',
  'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'
] as const;

// All legal areas we support
const ALL_LEGAL_AREAS: LegalCategory[] = [
  'family',
  'small-claims',
  'employment',
  'housing',
  'criminal',
  'cps',
  'workers-rights',
  'human-rights',
  'agency-complaints',
  'personal-injury',
];

// State-specific form mappings for all 50 states + DC
const STATE_FORMS: Record<string, Partial<Record<LegalCategory, string[]>>> = {
  AL: {
    'family': ['CS-41', 'CS-42', 'PS-12', 'DR-01'],
    'small-claims': ['SM-01', 'SM-02', 'District Court Claim'],
    'employment': ['UC-1', 'ALDOL Form', 'EEOC Charge'],
    'housing': ['LT-1', 'Eviction Complaint', 'Answer'],
    'criminal': ['Expungement Petition', 'CR-52'],
    'cps': ['DHR-1', 'Dependency Petition'],
    'workers-rights': ['WC-1', 'OSHA-7'],
    'human-rights': ['EEOC-5', 'Civil Rights Complaint'],
    'agency-complaints': ['Medical Board Complaint', 'Bar Complaint'],
  },
  AK: {
    'family': ['DR-100', 'DR-150', 'SHC-1', 'DV-100'],
    'small-claims': ['SC-100', 'SC-110', 'Small Claims Statement'],
    'employment': ['ESS UI Claim', 'EEOC Charge'],
    'housing': ['FED-1', 'Eviction Answer', 'RP-10'],
    'criminal': ['Expungement Motion', 'CR-100'],
    'cps': ['OCS Petition', 'CINA'],
    'workers-rights': ['WC Claim', 'OSHA-7'],
    'human-rights': ['HRC Complaint', 'EEOC-5'],
    'agency-complaints': ['Medical Board', 'Bar Association'],
  },
  AZ: {
    'family': ['DR-01', 'DRF-31', 'DR-101', 'DRDOM-01'],
    'small-claims': ['CVS-100', 'CVS-101', 'Justice Court'],
    'employment': ['DES UI Claim', 'ACRD Complaint', 'EEOC Charge'],
    'housing': ['FED Action', 'Answer in FED', 'LT-01'],
    'criminal': ['Set Aside Motion', 'Expungement'],
    'cps': ['DCS Petition', 'JV-001'],
    'workers-rights': ['ICA Claim', 'OSHA-7'],
    'human-rights': ['ACRD-1', 'EEOC-5'],
    'agency-complaints': ['BOMEX', 'State Bar'],
  },
  AR: {
    'family': ['DR-01', 'DR-12', 'Divorce Petition'],
    'small-claims': ['Small Claims Affidavit', 'DC-01'],
    'employment': ['DWS UI Claim', 'EEOC Charge'],
    'housing': ['Eviction Summons', 'UD Answer'],
    'criminal': ['Seal/Expunge Petition'],
    'cps': ['DCFS Petition', 'DN-01'],
    'workers-rights': ['WCC Claim', 'OSHA-7'],
    'human-rights': ['EEOC-5', 'Federal Complaint'],
    'agency-complaints': ['ASMB', 'State Bar Complaint'],
  },
  CA: {
    'family': ['FL-100', 'FL-110', 'FL-150', 'FL-300', 'DV-100'],
    'small-claims': ['SC-100', 'SC-104', 'SC-500'],
    'employment': ['DLSE-1', 'CRD Complaint', 'DWC-1'],
    'housing': ['UD-100', 'UD-105', 'SC-500A'],
    'criminal': ['CR-180', 'CR-181', 'CR-105'],
    'cps': ['JV-100', 'JV-180', 'JV-200'],
    'workers-rights': ['DIR-1', 'OSHA-7', 'WC-1'],
    'human-rights': ['CRD-1', 'OCR-1', 'EEOC-5'],
    'agency-complaints': ['PCC-1', 'MBC-1', 'SBA-1'],
  },
  CO: {
    'family': ['JDF-1101', 'JDF-1102', 'JDF-1103', 'JDF-1111'],
    'small-claims': ['JDF-250', 'JDF-251', 'County Court'],
    'employment': ['CDLE UI Claim', 'CCRD Complaint', 'EEOC Charge'],
    'housing': ['JDF-99', 'FED Answer', 'Eviction Action'],
    'criminal': ['JDF-500', 'Sealing Petition'],
    'cps': ['DHS Petition', 'JDF-401'],
    'workers-rights': ['WC Claim', 'OSHA-7'],
    'human-rights': ['CCRD-1', 'EEOC-5'],
    'agency-complaints': ['DORA Complaint', 'State Bar'],
  },
  CT: {
    'family': ['JD-FM-3', 'JD-FM-159', 'JD-FM-1'],
    'small-claims': ['JD-CV-40', 'JD-CV-1', 'Small Claims'],
    'employment': ['DOL UI Claim', 'CHRO Complaint', 'EEOC Charge'],
    'housing': ['JD-HM-1', 'Summary Process', 'Answer'],
    'criminal': ['Pardon Application', 'Erasure Form'],
    'cps': ['DCF Petition', 'JD-JM-1'],
    'workers-rights': ['WCC Form', 'OSHA-7'],
    'human-rights': ['CHRO-1', 'EEOC-5'],
    'agency-complaints': ['DPH Complaint', 'CBA Complaint'],
  },
  DE: {
    'family': ['Form 240', 'Petition for Divorce', 'PFA Petition'],
    'small-claims': ['JP Civil Complaint', 'SC Form'],
    'employment': ['DOL UI Claim', 'DDOL Complaint', 'EEOC Charge'],
    'housing': ['SC Summary Possession', 'Answer'],
    'criminal': ['Expungement Petition', 'Pardon Application'],
    'cps': ['DFS Petition', 'CJ-01'],
    'workers-rights': ['IAB Claim', 'OSHA-7'],
    'human-rights': ['DDOL Discrimination', 'EEOC-5'],
    'agency-complaints': ['Medical Board', 'Bar Complaint'],
  },
  DC: {
    'family': ['DOM-1', 'DRB-1', 'CPO Petition'],
    'small-claims': ['SC Form 1', 'Statement of Claim'],
    'employment': ['DOES UI Claim', 'OHR Complaint', 'EEOC Charge'],
    'housing': ['LT Complaint', 'Answer to LT', 'Tenant Petition'],
    'criminal': ['Motion to Seal', 'Expungement'],
    'cps': ['CFSA Petition', 'Neglect'],
    'workers-rights': ['WC Claim', 'OSHA-7'],
    'human-rights': ['OHR-1', 'EEOC-5'],
    'agency-complaints': ['DOH Complaint', 'Bar Complaint'],
  },
  FL: {
    'family': ['Form 12.901(a)', 'Form 12.901(b)(1)', 'Form 12.902(b)', 'Form 12.995(a)'],
    'small-claims': ['Statement of Claim', 'Summons', 'Affidavit of Non-Military Service'],
    'employment': ['DEO Claim', 'FCHR Complaint', 'EEOC Charge'],
    'housing': ['Eviction Summons', 'Answer to Eviction', 'Motion to Determine Rent'],
    'criminal': ['Motion to Seal', 'Motion to Expunge'],
    'cps': ['DCF-1', 'Dependency Petition'],
    'workers-rights': ['DFS-F2-DWC-1', 'OSHA-7'],
    'human-rights': ['FCHR-1', 'EEOC-5'],
    'agency-complaints': ['DOH-MQA', 'FDLE Complaint'],
  },
  GA: {
    'family': ['Domestic Relations Filing', 'Divorce Petition', 'TPO'],
    'small-claims': ['Magistrate Court Claim', 'Statement of Claim'],
    'employment': ['GDOL UI Claim', 'GCEO Complaint', 'EEOC Charge'],
    'housing': ['Dispossessory Affidavit', 'Answer'],
    'criminal': ['Record Restriction', 'Expungement Petition'],
    'cps': ['DFCS Petition', 'Deprivation'],
    'workers-rights': ['SBWC Claim', 'OSHA-7'],
    'human-rights': ['GCEO-1', 'EEOC-5'],
    'agency-complaints': ['GCMB', 'State Bar'],
  },
  HI: {
    'family': ['1F-P-800', '1F-P-836', 'TRO Petition'],
    'small-claims': ['SC-DC Form', 'Small Claims'],
    'employment': ['DOL UI Claim', 'HCRC Complaint', 'EEOC Charge'],
    'housing': ['DC-TG Form', 'Summary Possession'],
    'criminal': ['Expungement Petition'],
    'cps': ['DHS Petition', 'CPS'],
    'workers-rights': ['DLIR Claim', 'OSHA-7'],
    'human-rights': ['HCRC-1', 'EEOC-5'],
    'agency-complaints': ['DCCA', 'State Bar'],
  },
  ID: {
    'family': ['CAO FL-1', 'Divorce Petition', 'Protection Order'],
    'small-claims': ['CAO SC-1', 'Small Claims'],
    'employment': ['DOL UI Claim', 'IHRC Complaint', 'EEOC Charge'],
    'housing': ['Eviction Summons', 'Answer'],
    'criminal': ['Expungement Motion'],
    'cps': ['DHW Petition', 'CPA'],
    'workers-rights': ['IC Claim', 'OSHA-7'],
    'human-rights': ['IHRC-1', 'EEOC-5'],
    'agency-complaints': ['BOM', 'State Bar'],
  },
  IL: {
    'family': ['Dissolution Petition', 'Order of Protection', 'Custody'],
    'small-claims': ['Small Claims Complaint', 'Pro Se'],
    'employment': ['IDES UI Claim', 'IDHR Complaint', 'EEOC Charge'],
    'housing': ['Forcible Entry', 'Eviction Complaint', 'Answer'],
    'criminal': ['Expungement Petition', 'Sealing Petition'],
    'cps': ['DCFS Petition', 'Neglect'],
    'workers-rights': ['IWCC Claim', 'OSHA-7'],
    'human-rights': ['IDHR-1', 'EEOC-5'],
    'agency-complaints': ['IDFPR', 'ARDC'],
  },
  IN: {
    'family': ['Dissolution Petition', 'PO Form', 'Custody'],
    'small-claims': ['SC-1', 'Small Claims Statement'],
    'employment': ['DWD UI Claim', 'ICRC Complaint', 'EEOC Charge'],
    'housing': ['Eviction Summons', 'Notice to Quit'],
    'criminal': ['Expungement Petition'],
    'cps': ['DCS Petition', 'CHINS'],
    'workers-rights': ['WCB Claim', 'OSHA-7'],
    'human-rights': ['ICRC-1', 'EEOC-5'],
    'agency-complaints': ['IPLA', 'State Bar'],
  },
  IA: {
    'family': ['Dissolution Petition', 'Protection Order', 'Custody'],
    'small-claims': ['SC Form', 'Original Notice'],
    'employment': ['IWD UI Claim', 'ICRC Complaint', 'EEOC Charge'],
    'housing': ['FED Petition', 'Eviction'],
    'criminal': ['Expungement Application'],
    'cps': ['DHS Petition', 'CINA'],
    'workers-rights': ['WC Claim', 'OSHA-7'],
    'human-rights': ['ICRC-1', 'EEOC-5'],
    'agency-complaints': ['IBOM', 'State Bar'],
  },
  KS: {
    'family': ['Petition for Divorce', 'PFA', 'Custody'],
    'small-claims': ['SC Petition', 'Limited Actions'],
    'employment': ['KDOL UI Claim', 'KHRC Complaint', 'EEOC Charge'],
    'housing': ['Eviction Petition', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DCF Petition', 'CINC'],
    'workers-rights': ['WC Claim', 'OSHA-7'],
    'human-rights': ['KHRC-1', 'EEOC-5'],
    'agency-complaints': ['KSBHA', 'State Bar'],
  },
  KY: {
    'family': ['AOC-238', 'Dissolution Petition', 'EPO/DVO'],
    'small-claims': ['AOC-175', 'Small Claims'],
    'employment': ['OUI UI Claim', 'KCHR Complaint', 'EEOC Charge'],
    'housing': ['Forcible Detainer', 'Answer'],
    'criminal': ['Expungement Motion', 'AOC-496'],
    'cps': ['DCBS Petition', 'DNA'],
    'workers-rights': ['DWC Claim', 'OSHA-7'],
    'human-rights': ['KCHR-1', 'EEOC-5'],
    'agency-complaints': ['KBML', 'KBA'],
  },
  LA: {
    'family': ['Petition for Divorce', 'PO Request', 'Custody'],
    'small-claims': ['Small Claims Petition', 'City Court'],
    'employment': ['LWC UI Claim', 'LCHR Complaint', 'EEOC Charge'],
    'housing': ['Rule to Show Cause', 'Eviction'],
    'criminal': ['Expungement Motion'],
    'cps': ['DCFS Petition', 'CINC'],
    'workers-rights': ['OWCA Claim', 'OSHA-7'],
    'human-rights': ['LCHR-1', 'EEOC-5'],
    'agency-complaints': ['LSBME', 'LSBA'],
  },
  ME: {
    'family': ['FM-001', 'Divorce Complaint', 'Protection Order'],
    'small-claims': ['SC-001', 'Small Claims Statement'],
    'employment': ['DOL UI Claim', 'MHRC Complaint', 'EEOC Charge'],
    'housing': ['FED Summons', 'Answer'],
    'criminal': ['Expungement Motion'],
    'cps': ['DHHS Petition', 'Jeopardy'],
    'workers-rights': ['WCB Claim', 'OSHA-7'],
    'human-rights': ['MHRC-1', 'EEOC-5'],
    'agency-complaints': ['BOLIM', 'BOB'],
  },
  MD: {
    'family': ['CC-DR-20', 'Divorce Complaint', 'Protective Order'],
    'small-claims': ['DC-CV-001', 'Small Claims'],
    'employment': ['DOL UI Claim', 'MCCR Complaint', 'EEOC Charge'],
    'housing': ['Failure to Pay Rent', 'Complaint'],
    'criminal': ['Expungement Petition'],
    'cps': ['DSS Petition', 'CINA'],
    'workers-rights': ['WCC Claim', 'OSHA-7'],
    'human-rights': ['MCCR-1', 'EEOC-5'],
    'agency-complaints': ['MBP', 'MSBA'],
  },
  MA: {
    'family': ['CJ-D 101', 'Divorce Complaint', '209A Petition'],
    'small-claims': ['SC-1', 'Statement of Claim'],
    'employment': ['DUA UI Claim', 'MCAD Complaint', 'EEOC Charge'],
    'housing': ['Summary Process', 'Answer'],
    'criminal': ['Sealing Petition', 'Expungement'],
    'cps': ['DCF Petition', 'Care and Protection'],
    'workers-rights': ['DIA Claim', 'OSHA-7'],
    'human-rights': ['MCAD-1', 'EEOC-5'],
    'agency-complaints': ['BRM', 'BBO'],
  },
  MI: {
    'family': ['MC-01', 'Divorce Complaint', 'PPO Petition'],
    'small-claims': ['DC-84', 'Small Claims Affidavit'],
    'employment': ['UIA UI Claim', 'MDCR Complaint', 'EEOC Charge'],
    'housing': ['DC-102', 'Summons and Complaint'],
    'criminal': ['MC-227', 'Expungement'],
    'cps': ['DHHS Petition', 'Abuse/Neglect'],
    'workers-rights': ['WC Claim', 'OSHA-7'],
    'human-rights': ['MDCR-1', 'EEOC-5'],
    'agency-complaints': ['LARA', 'SBM'],
  },
  MN: {
    'family': ['IFP Petition', 'Dissolution', 'OFP'],
    'small-claims': ['Conciliation Court', 'Statement of Claim'],
    'employment': ['DEED UI Claim', 'MDHR Complaint', 'EEOC Charge'],
    'housing': ['Eviction Summons', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DHS Petition', 'CHIPS'],
    'workers-rights': ['DLI Claim', 'OSHA-7'],
    'human-rights': ['MDHR-1', 'EEOC-5'],
    'agency-complaints': ['BMP', 'OLPR'],
  },
  MS: {
    'family': ['Divorce Complaint', 'Protective Order', 'Custody'],
    'small-claims': ['Justice Court Claim'],
    'employment': ['MDES UI Claim', 'EEOC Charge'],
    'housing': ['Eviction Affidavit', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['MDCPS Petition', 'Youth Court'],
    'workers-rights': ['WCC Claim', 'OSHA-7'],
    'human-rights': ['EEOC-5'],
    'agency-complaints': ['MSBML', 'MSB'],
  },
  MO: {
    'family': ['Form 14', 'Dissolution Petition', 'Ex Parte'],
    'small-claims': ['Associate Division', 'Statement of Claim'],
    'employment': ['DES UI Claim', 'MCHR Complaint', 'EEOC Charge'],
    'housing': ['Rent and Possession', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['CD Petition', 'Abuse/Neglect'],
    'workers-rights': ['DWC Claim', 'OSHA-7'],
    'human-rights': ['MCHR-1', 'EEOC-5'],
    'agency-complaints': ['BSRB', 'MOBAR'],
  },
  MT: {
    'family': ['DR-100', 'Dissolution Petition', 'Order of Protection'],
    'small-claims': ['DC-SC', 'Small Claims'],
    'employment': ['DLI UI Claim', 'HRB Complaint', 'EEOC Charge'],
    'housing': ['Eviction Summons', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DPHHS Petition', 'Abuse/Neglect'],
    'workers-rights': ['ERD Claim', 'OSHA-7'],
    'human-rights': ['HRB-1', 'EEOC-5'],
    'agency-complaints': ['BMP', 'State Bar'],
  },
  NE: {
    'family': ['DC 6:5(1)', 'Dissolution Complaint', 'Protection Order'],
    'small-claims': ['CC 4:1', 'County Court Claim'],
    'employment': ['DOL UI Claim', 'NEOC Complaint', 'EEOC Charge'],
    'housing': ['Restitution Complaint', 'Answer'],
    'criminal': ['Set Aside Petition'],
    'cps': ['DHHS Petition', 'Juvenile'],
    'workers-rights': ['WCC Claim', 'OSHA-7'],
    'human-rights': ['NEOC-1', 'EEOC-5'],
    'agency-complaints': ['DHHS', 'NSBA'],
  },
  NV: {
    'family': ['Divorce Complaint', 'TPO Petition', 'Custody'],
    'small-claims': ['Justice Court', 'Small Claims Statement'],
    'employment': ['DETR UI Claim', 'NERC Complaint', 'EEOC Charge'],
    'housing': ['Summary Eviction', 'Answer'],
    'criminal': ['Sealing Petition'],
    'cps': ['DCFS Petition', 'Abuse/Neglect'],
    'workers-rights': ['DIR Claim', 'OSHA-7'],
    'human-rights': ['NERC-1', 'EEOC-5'],
    'agency-complaints': ['BME', 'State Bar'],
  },
  NH: {
    'family': ['NHJB-2001', 'Divorce Petition', 'DV Petition'],
    'small-claims': ['NHJB-2062', 'Small Claims'],
    'employment': ['NHES UI Claim', 'HRC Complaint', 'EEOC Charge'],
    'housing': ['LT Writ', 'Answer'],
    'criminal': ['Annulment Petition'],
    'cps': ['DCYF Petition', 'Abuse/Neglect'],
    'workers-rights': ['DOL Claim', 'OSHA-7'],
    'human-rights': ['HRC-1', 'EEOC-5'],
    'agency-complaints': ['BMP', 'NHBA'],
  },
  NJ: {
    'family': ['FM-1', 'Divorce Complaint', 'TRO Petition'],
    'small-claims': ['SC-1', 'Small Claims Complaint'],
    'employment': ['LWD UI Claim', 'DCR Complaint', 'EEOC Charge'],
    'housing': ['LT Complaint', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DCF Petition', 'Abuse/Neglect'],
    'workers-rights': ['WC Claim', 'OSHA-7'],
    'human-rights': ['DCR-1', 'EEOC-5'],
    'agency-complaints': ['BME', 'State Bar'],
  },
  NM: {
    'family': ['4-201', 'Dissolution Petition', 'Order of Protection'],
    'small-claims': ['4-201', 'Metropolitan Small Claims'],
    'employment': ['DWS UI Claim', 'HRD Complaint', 'EEOC Charge'],
    'housing': ['Owner Petition', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['CYFD Petition', 'Abuse/Neglect'],
    'workers-rights': ['WCA Claim', 'OSHA-7'],
    'human-rights': ['HRD-1', 'EEOC-5'],
    'agency-complaints': ['MBE', 'State Bar'],
  },
  NY: {
    'family': ['UD-2', 'UD-11', 'Order of Protection Petition', 'Custody Petition'],
    'small-claims': ['CIV-SC-50', 'Commercial Claims Form', 'Motion to Vacate Default'],
    'employment': ['DOL UI-1', 'DOL LS-223', 'DHR Complaint'],
    'housing': ['NYLP-1', 'Answer in Eviction', 'HP Action'],
    'criminal': ['CPL 160.59 Motion', 'Certificate of Relief'],
    'cps': ['Family Court Petition', 'JD-1'],
    'workers-rights': ['WCB-C3', 'OSHA-7'],
    'human-rights': ['DHR-1', 'EEOC-5'],
    'agency-complaints': ['OPMC-1', 'CCRB-1'],
  },
  NC: {
    'family': ['AOC-CV-200', 'Divorce Complaint', 'DVPO'],
    'small-claims': ['AOC-CVM-100', 'Magistrate'],
    'employment': ['DES UI Claim', 'EEOC Charge'],
    'housing': ['Summary Ejectment', 'Answer'],
    'criminal': ['Expunction Petition'],
    'cps': ['DSS Petition', 'Abuse/Neglect'],
    'workers-rights': ['IC Claim', 'OSHA-7'],
    'human-rights': ['EEOC-5'],
    'agency-complaints': ['NCMB', 'State Bar'],
  },
  ND: {
    'family': ['Divorce Summons', 'Protection Order', 'Custody'],
    'small-claims': ['SC-1', 'Small Claims Statement'],
    'employment': ['JSND UI Claim', 'DHR Complaint', 'EEOC Charge'],
    'housing': ['Eviction Summons', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DHS Petition', 'Deprivation'],
    'workers-rights': ['WSI Claim', 'OSHA-7'],
    'human-rights': ['DHR-1', 'EEOC-5'],
    'agency-complaints': ['BME', 'SBAND'],
  },
  OH: {
    'family': ['DR-01', 'Divorce Complaint', 'CPO Petition'],
    'small-claims': ['SC-1', 'Small Claims Complaint'],
    'employment': ['ODJFS UI Claim', 'OCRC Complaint', 'EEOC Charge'],
    'housing': ['Forcible Entry', 'Answer'],
    'criminal': ['Sealing Application'],
    'cps': ['JFS Petition', 'Abuse/Neglect'],
    'workers-rights': ['BWC Claim', 'OSHA-7'],
    'human-rights': ['OCRC-1', 'EEOC-5'],
    'agency-complaints': ['SMBO', 'OSBA'],
  },
  OK: {
    'family': ['Divorce Petition', 'VPO Petition', 'Custody'],
    'small-claims': ['SC-1', 'Small Claims Affidavit'],
    'employment': ['OESC UI Claim', 'EEOC Charge'],
    'housing': ['FED Action', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DHS Petition', 'Deprived'],
    'workers-rights': ['WCC Claim', 'OSHA-7'],
    'human-rights': ['EEOC-5'],
    'agency-complaints': ['OSBMLS', 'OBA'],
  },
  OR: {
    'family': ['Dissolution Petition', 'FAPA', 'Custody'],
    'small-claims': ['SC-1', 'Small Claims Statement'],
    'employment': ['OED UI Claim', 'BOLI Complaint', 'EEOC Charge'],
    'housing': ['FED Complaint', 'Answer'],
    'criminal': ['Set Aside Motion'],
    'cps': ['DHS Petition', 'Dependency'],
    'workers-rights': ['WCB Claim', 'OSHA-7'],
    'human-rights': ['BOLI-1', 'EEOC-5'],
    'agency-complaints': ['OMB', 'OSB'],
  },
  PA: {
    'family': ['Divorce Complaint', 'PFA Petition', 'Custody'],
    'small-claims': ['MDJ Complaint', 'Statement of Claim'],
    'employment': ['UC Claim', 'PHRC Complaint', 'EEOC Charge'],
    'housing': ['LT Complaint', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DHS Petition', 'Dependency'],
    'workers-rights': ['WC Claim', 'OSHA-7'],
    'human-rights': ['PHRC-1', 'EEOC-5'],
    'agency-complaints': ['BPOA', 'PBA'],
  },
  RI: {
    'family': ['DR-1', 'Divorce Complaint', 'Restraining Order'],
    'small-claims': ['SC-1', 'Small Claims Statement'],
    'employment': ['DLT UI Claim', 'RICHR Complaint', 'EEOC Charge'],
    'housing': ['Eviction Complaint', 'Answer'],
    'criminal': ['Expungement Motion'],
    'cps': ['DCYF Petition', 'Abuse/Neglect'],
    'workers-rights': ['WCC Claim', 'OSHA-7'],
    'human-rights': ['RICHR-1', 'EEOC-5'],
    'agency-complaints': ['DOH', 'State Bar'],
  },
  SC: {
    'family': ['SCCA-400', 'Divorce Complaint', 'Order of Protection'],
    'small-claims': ['Magistrate Claim', 'Statement'],
    'employment': ['DEW UI Claim', 'SCHAC Complaint', 'EEOC Charge'],
    'housing': ['Ejectment', 'Rule to Vacate'],
    'criminal': ['Expungement Application'],
    'cps': ['DSS Petition', 'Abuse/Neglect'],
    'workers-rights': ['WCC Claim', 'OSHA-7'],
    'human-rights': ['SCHAC-1', 'EEOC-5'],
    'agency-complaints': ['LLR', 'State Bar'],
  },
  SD: {
    'family': ['Divorce Summons', 'Protection Order', 'Custody'],
    'small-claims': ['Small Claims Filing'],
    'employment': ['DLR UI Claim', 'EEOC Charge'],
    'housing': ['Eviction Summons', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DSS Petition', 'Abuse/Neglect'],
    'workers-rights': ['DLR Claim', 'OSHA-7'],
    'human-rights': ['EEOC-5'],
    'agency-complaints': ['BMP', 'State Bar'],
  },
  TN: {
    'family': ['Divorce Complaint', 'Order of Protection', 'Custody'],
    'small-claims': ['GS Civil Warrant', 'Statement'],
    'employment': ['DOL UI Claim', 'THRC Complaint', 'EEOC Charge'],
    'housing': ['Detainer Warrant', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DCS Petition', 'Dependent/Neglected'],
    'workers-rights': ['BWC Claim', 'OSHA-7'],
    'human-rights': ['THRC-1', 'EEOC-5'],
    'agency-complaints': ['DOH', 'BPR'],
  },
  TX: {
    'family': ['Original Petition for Divorce', 'SAPCR Petition', 'Application for Protective Order'],
    'small-claims': ['Petition (Small Claims)', 'Citation', 'Answer'],
    'employment': ['TWC Initial Claim', 'TWC Wage Claim', 'EEOC Charge'],
    'housing': ['Eviction Petition', 'Answer to Eviction', 'Request for Jury Trial'],
    'criminal': ['Expunction Petition', 'Order of Nondisclosure'],
    'cps': ['DFPS-2200', 'DFPS-K-908-2254'],
    'workers-rights': ['TWC-1', 'OSHA-7', 'TDI-1'],
    'human-rights': ['THR-1', 'EEOC-5'],
    'agency-complaints': ['TSBME-1', 'TBLS-1'],
  },
  UT: {
    'family': ['Divorce Petition', 'Protective Order', 'Custody'],
    'small-claims': ['SC-1', 'Statement of Claim'],
    'employment': ['DWS UI Claim', 'UALD Complaint', 'EEOC Charge'],
    'housing': ['Eviction Complaint', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DCFS Petition', 'Abuse/Neglect'],
    'workers-rights': ['LCU Claim', 'OSHA-7'],
    'human-rights': ['UALD-1', 'EEOC-5'],
    'agency-complaints': ['DOPL', 'State Bar'],
  },
  VT: {
    'family': ['800-FO', 'Divorce Complaint', 'RFA Petition'],
    'small-claims': ['100-SC', 'Statement of Claim'],
    'employment': ['DOL UI Claim', 'HRC Complaint', 'EEOC Charge'],
    'housing': ['Eviction Complaint', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DCF Petition', 'CHINS'],
    'workers-rights': ['WC Claim', 'VOSHA'],
    'human-rights': ['HRC-1', 'EEOC-5'],
    'agency-complaints': ['BME', 'PRB'],
  },
  VA: {
    'family': ['DC-610', 'Divorce Complaint', 'Protective Order'],
    'small-claims': ['DC-401', 'Warrant in Debt'],
    'employment': ['VEC UI Claim', 'EEOC Charge'],
    'housing': ['UD Summons', 'Unlawful Detainer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DSS Petition', 'CHINS'],
    'workers-rights': ['VWC Claim', 'OSHA-7'],
    'human-rights': ['EEOC-5'],
    'agency-complaints': ['DHP', 'VSB'],
  },
  WA: {
    'family': ['FL Dissolution', 'Protection Order', 'Parenting Plan'],
    'small-claims': ['SC-100', 'Small Claims Notice'],
    'employment': ['ESD UI Claim', 'WSHRC Complaint', 'EEOC Charge'],
    'housing': ['Unlawful Detainer', 'Answer'],
    'criminal': ['Vacation Motion'],
    'cps': ['DCYF Petition', 'Dependency'],
    'workers-rights': ['LNI Claim', 'WISHA'],
    'human-rights': ['WSHRC-1', 'EEOC-5'],
    'agency-complaints': ['DOH', 'WSBA'],
  },
  WV: {
    'family': ['SCA-FC-1', 'Divorce Petition', 'DVP Petition'],
    'small-claims': ['Magistrate Claim'],
    'employment': ['Workforce UI Claim', 'WVHRC Complaint', 'EEOC Charge'],
    'housing': ['Wrongful Occupation', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DHHR Petition', 'Abuse/Neglect'],
    'workers-rights': ['IC Claim', 'OSHA-7'],
    'human-rights': ['WVHRC-1', 'EEOC-5'],
    'agency-complaints': ['BOM', 'State Bar'],
  },
  WI: {
    'family': ['FA-4101', 'Divorce Petition', 'TRO/Injunction'],
    'small-claims': ['SC-500', 'Statement of Claim'],
    'employment': ['DWD UI Claim', 'ERD Complaint', 'EEOC Charge'],
    'housing': ['Eviction Summons', 'Answer'],
    'criminal': ['Expungement Motion'],
    'cps': ['DCF Petition', 'CHIPS'],
    'workers-rights': ['DWD Claim', 'OSHA-7'],
    'human-rights': ['ERD-1', 'EEOC-5'],
    'agency-complaints': ['DSPS', 'State Bar'],
  },
  WY: {
    'family': ['Divorce Complaint', 'Order of Protection', 'Custody'],
    'small-claims': ['SC-1', 'Statement of Claim'],
    'employment': ['DOE UI Claim', 'EEOC Charge'],
    'housing': ['FED Complaint', 'Answer'],
    'criminal': ['Expungement Petition'],
    'cps': ['DFS Petition', 'Abuse/Neglect'],
    'workers-rights': ['WD Claim', 'OSHA-7'],
    'human-rights': ['EEOC-5'],
    'agency-complaints': ['BM', 'State Bar'],
  },
};

// State-specific court mappings for all 50 states + DC
const STATE_COURTS: Record<string, Partial<Record<LegalCategory, string[]>>> = {
  AL: {
    'family': ['Circuit Court - Family Division', 'District Court'],
    'small-claims': ['District Court - Small Claims', 'Small Claims Court'],
    'employment': ['Alabama DOL', 'EEOC Birmingham', 'Circuit Court'],
    'housing': ['District Court', 'Circuit Court'],
    'criminal': ['Circuit Court', 'District Court'],
    'cps': ['Juvenile Court', 'Family Court'],
    'workers-rights': ['Workers Comp Court', 'OSHA'],
    'human-rights': ['EEOC', 'Federal Court'],
    'agency-complaints': ['Medical Licensure', 'State Bar'],
  },
  AK: {
    'family': ['Superior Court', 'District Court'],
    'small-claims': ['District Court - Small Claims', 'Small Claims Court'],
    'employment': ['Alaska DOL', 'EEOC Seattle', 'Superior Court'],
    'housing': ['District Court', 'Superior Court'],
    'criminal': ['Superior Court', 'District Court'],
    'cps': ['Superior Court - CINA'],
    'workers-rights': ['Workers Comp Board', 'OSHA'],
    'human-rights': ['HRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['Medical Board', 'Bar Association'],
  },
  AZ: {
    'family': ['Superior Court - Family', 'Justice Court'],
    'small-claims': ['Justice Court', 'Small Claims Division'],
    'employment': ['ICA', 'ACRD', 'EEOC Phoenix', 'Superior Court'],
    'housing': ['Justice Court', 'Superior Court'],
    'criminal': ['Superior Court', 'Justice Court', 'Municipal Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['ICA', 'OSHA'],
    'human-rights': ['ACRD', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BOMEX', 'State Bar'],
  },
  AR: {
    'family': ['Circuit Court - Domestic Relations'],
    'small-claims': ['District Court - Small Claims'],
    'employment': ['DWS', 'EEOC Little Rock', 'Circuit Court'],
    'housing': ['District Court', 'Circuit Court'],
    'criminal': ['Circuit Court', 'District Court'],
    'cps': ['Juvenile Division'],
    'workers-rights': ['WCC', 'OSHA'],
    'human-rights': ['EEOC', 'Federal Court'],
    'agency-complaints': ['Medical Board', 'Bar Association'],
  },
  CA: {
    'family': ['Superior Court - Family Division'],
    'small-claims': ['Small Claims Court'],
    'employment': ['Labor Commissioner', 'Civil Rights Dept', 'Superior Court'],
    'housing': ['Superior Court - Unlawful Detainer', 'Small Claims Court'],
    'criminal': ['Superior Court - Criminal Division'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['DIR', 'WCAB', 'OSHA'],
    'human-rights': ['Civil Rights Dept', 'EEOC', 'Federal Court'],
    'agency-complaints': ['Medical Board', 'State Bar', 'POST'],
  },
  CO: {
    'family': ['District Court - Domestic Relations'],
    'small-claims': ['County Court - Small Claims'],
    'employment': ['CDLE', 'CCRD', 'EEOC Denver', 'District Court'],
    'housing': ['County Court', 'District Court'],
    'criminal': ['District Court', 'County Court'],
    'cps': ['District Court - Juvenile'],
    'workers-rights': ['DOWC', 'OSHA'],
    'human-rights': ['CCRD', 'EEOC', 'Federal Court'],
    'agency-complaints': ['DORA', 'State Bar'],
  },
  CT: {
    'family': ['Superior Court - Family Division'],
    'small-claims': ['Small Claims - Superior Court'],
    'employment': ['DOL', 'CHRO', 'EEOC', 'Superior Court'],
    'housing': ['Superior Court - Housing Session'],
    'criminal': ['Superior Court - Criminal'],
    'cps': ['Superior Court - Juvenile'],
    'workers-rights': ['WCC', 'OSHA'],
    'human-rights': ['CHRO', 'EEOC', 'Federal Court'],
    'agency-complaints': ['DPH', 'CBA'],
  },
  DE: {
    'family': ['Family Court'],
    'small-claims': ['Justice of the Peace Court'],
    'employment': ['DOL', 'DDOL', 'EEOC', 'Superior Court'],
    'housing': ['Justice of the Peace Court', 'Superior Court'],
    'criminal': ['Superior Court', 'Court of Common Pleas'],
    'cps': ['Family Court'],
    'workers-rights': ['IAB', 'OSHA'],
    'human-rights': ['DDOL', 'EEOC', 'Federal Court'],
    'agency-complaints': ['Medical Board', 'State Bar'],
  },
  DC: {
    'family': ['DC Superior Court - Family Division'],
    'small-claims': ['DC Superior Court - Small Claims'],
    'employment': ['DOES', 'OHR', 'EEOC', 'Superior Court'],
    'housing': ['DC Superior Court - Landlord Tenant'],
    'criminal': ['DC Superior Court - Criminal'],
    'cps': ['DC Superior Court - Family'],
    'workers-rights': ['OWC', 'OSHA'],
    'human-rights': ['OHR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['DOH', 'DC Bar'],
  },
  FL: {
    'family': ['Circuit Court - Family Division'],
    'small-claims': ['County Court - Small Claims'],
    'employment': ['DEO', 'FCHR', 'EEOC', 'Circuit Court'],
    'housing': ['County Court', 'Circuit Court'],
    'criminal': ['Circuit Court', 'County Court'],
    'cps': ['Circuit Court - Dependency'],
    'workers-rights': ['DFS', 'OSHA'],
    'human-rights': ['FCHR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['DOH', 'State Bar', 'FDLE'],
  },
  GA: {
    'family': ['Superior Court - Family Division'],
    'small-claims': ['Magistrate Court'],
    'employment': ['GDOL', 'GCEO', 'EEOC Atlanta', 'Superior Court'],
    'housing': ['Magistrate Court', 'State Court'],
    'criminal': ['Superior Court', 'State Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['SBWC', 'OSHA'],
    'human-rights': ['GCEO', 'EEOC', 'Federal Court'],
    'agency-complaints': ['GCMB', 'State Bar'],
  },
  HI: {
    'family': ['Family Court'],
    'small-claims': ['District Court - Small Claims'],
    'employment': ['DLIR', 'HCRC', 'EEOC', 'Circuit Court'],
    'housing': ['District Court'],
    'criminal': ['Circuit Court', 'District Court'],
    'cps': ['Family Court'],
    'workers-rights': ['DLIR', 'HIOSH'],
    'human-rights': ['HCRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['DCCA', 'State Bar'],
  },
  ID: {
    'family': ['District Court - Family'],
    'small-claims': ['Small Claims Department'],
    'employment': ['DOL', 'IHRC', 'EEOC', 'District Court'],
    'housing': ['Magistrate Division', 'District Court'],
    'criminal': ['District Court', 'Magistrate Division'],
    'cps': ['Magistrate Division'],
    'workers-rights': ['IC', 'OSHA'],
    'human-rights': ['IHRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BOM', 'State Bar'],
  },
  IL: {
    'family': ['Circuit Court - Domestic Relations'],
    'small-claims': ['Circuit Court - Small Claims'],
    'employment': ['IDES', 'IDHR', 'EEOC Chicago', 'Circuit Court'],
    'housing': ['Circuit Court - Eviction'],
    'criminal': ['Circuit Court - Criminal'],
    'cps': ['Circuit Court - Juvenile'],
    'workers-rights': ['IWCC', 'OSHA'],
    'human-rights': ['IDHR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['IDFPR', 'ARDC'],
  },
  IN: {
    'family': ['Circuit/Superior Court - Family'],
    'small-claims': ['Small Claims Court'],
    'employment': ['DWD', 'ICRC', 'EEOC Indianapolis', 'Circuit Court'],
    'housing': ['Small Claims', 'Circuit Court'],
    'criminal': ['Circuit/Superior Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['WCB', 'IOSHA'],
    'human-rights': ['ICRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['IPLA', 'State Bar'],
  },
  IA: {
    'family': ['District Court'],
    'small-claims': ['Small Claims Court'],
    'employment': ['IWD', 'ICRC', 'EEOC', 'District Court'],
    'housing': ['District Court'],
    'criminal': ['District Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['DWC', 'IOSH'],
    'human-rights': ['ICRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['IBOM', 'State Bar'],
  },
  KS: {
    'family': ['District Court - Domestic'],
    'small-claims': ['District Court - Limited Actions'],
    'employment': ['KDOL', 'KHRC', 'EEOC Kansas City', 'District Court'],
    'housing': ['District Court'],
    'criminal': ['District Court'],
    'cps': ['District Court - CINC'],
    'workers-rights': ['DWC', 'OSHA'],
    'human-rights': ['KHRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['KSBHA', 'State Bar'],
  },
  KY: {
    'family': ['Family Court', 'Circuit Court'],
    'small-claims': ['Small Claims Division - District Court'],
    'employment': ['OUI', 'KCHR', 'EEOC Louisville', 'Circuit Court'],
    'housing': ['District Court'],
    'criminal': ['Circuit Court', 'District Court'],
    'cps': ['Family Court'],
    'workers-rights': ['DWC', 'KYOSH'],
    'human-rights': ['KCHR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['KBML', 'KBA'],
  },
  LA: {
    'family': ['Family Court', 'District Court'],
    'small-claims': ['City Court', 'Justice of the Peace'],
    'employment': ['LWC', 'LCHR', 'EEOC New Orleans', 'District Court'],
    'housing': ['City Court', 'District Court'],
    'criminal': ['District Court', 'City Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['OWCA', 'OSHA'],
    'human-rights': ['LCHR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['LSBME', 'LSBA'],
  },
  ME: {
    'family': ['District Court - Family'],
    'small-claims': ['Small Claims - District Court'],
    'employment': ['DOL', 'MHRC', 'EEOC', 'Superior Court'],
    'housing': ['District Court'],
    'criminal': ['Superior Court', 'District Court'],
    'cps': ['District Court'],
    'workers-rights': ['WCB', 'OSHA'],
    'human-rights': ['MHRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BOLIM', 'BOB'],
  },
  MD: {
    'family': ['Circuit Court - Family Division'],
    'small-claims': ['District Court - Small Claims'],
    'employment': ['DOL', 'MCCR', 'EEOC Baltimore', 'Circuit Court'],
    'housing': ['District Court'],
    'criminal': ['Circuit Court', 'District Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['WCC', 'MOSH'],
    'human-rights': ['MCCR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['MBP', 'MSBA'],
  },
  MA: {
    'family': ['Probate and Family Court'],
    'small-claims': ['District Court - Small Claims', 'Boston Municipal Court'],
    'employment': ['DUA', 'MCAD', 'EEOC Boston', 'Superior Court'],
    'housing': ['Housing Court', 'District Court'],
    'criminal': ['Superior Court', 'District Court', 'BMC'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['DIA', 'OSHA'],
    'human-rights': ['MCAD', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BRM', 'BBO'],
  },
  MI: {
    'family': ['Circuit Court - Family Division'],
    'small-claims': ['District Court - Small Claims'],
    'employment': ['UIA', 'MDCR', 'EEOC Detroit', 'Circuit Court'],
    'housing': ['District Court'],
    'criminal': ['Circuit Court', 'District Court'],
    'cps': ['Family Court'],
    'workers-rights': ['WCC', 'MIOSHA'],
    'human-rights': ['MDCR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['LARA', 'SBM'],
  },
  MN: {
    'family': ['District Court - Family'],
    'small-claims': ['Conciliation Court'],
    'employment': ['DEED', 'MDHR', 'EEOC Minneapolis', 'District Court'],
    'housing': ['District Court - Housing'],
    'criminal': ['District Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['DLI', 'MNOSHA'],
    'human-rights': ['MDHR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BMP', 'OLPR'],
  },
  MS: {
    'family': ['Chancery Court'],
    'small-claims': ['Justice Court'],
    'employment': ['MDES', 'EEOC Jackson', 'Circuit Court'],
    'housing': ['Justice Court', 'County Court'],
    'criminal': ['Circuit Court', 'County Court'],
    'cps': ['Youth Court'],
    'workers-rights': ['WCC', 'OSHA'],
    'human-rights': ['EEOC', 'Federal Court'],
    'agency-complaints': ['MSBML', 'MSB'],
  },
  MO: {
    'family': ['Circuit Court - Family Division'],
    'small-claims': ['Circuit Court - Associate Division'],
    'employment': ['DES', 'MCHR', 'EEOC St Louis', 'Circuit Court'],
    'housing': ['Associate Circuit Court'],
    'criminal': ['Circuit Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['DWC', 'OSHA'],
    'human-rights': ['MCHR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BSRB', 'MOBAR'],
  },
  MT: {
    'family': ['District Court'],
    'small-claims': ['Justice Court', 'Small Claims'],
    'employment': ['DLI', 'HRB', 'EEOC', 'District Court'],
    'housing': ['Justice Court', 'District Court'],
    'criminal': ['District Court', 'Justice Court'],
    'cps': ['District Court - Youth Court'],
    'workers-rights': ['ERD', 'OSHA'],
    'human-rights': ['HRB', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BMP', 'State Bar'],
  },
  NE: {
    'family': ['District Court'],
    'small-claims': ['County Court'],
    'employment': ['DOL', 'NEOC', 'EEOC', 'District Court'],
    'housing': ['County Court'],
    'criminal': ['District Court', 'County Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['WCC', 'OSHA'],
    'human-rights': ['NEOC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['DHHS', 'NSBA'],
  },
  NV: {
    'family': ['District Court - Family Division'],
    'small-claims': ['Justice Court - Small Claims'],
    'employment': ['DETR', 'NERC', 'EEOC Las Vegas', 'District Court'],
    'housing': ['Justice Court'],
    'criminal': ['District Court', 'Justice Court'],
    'cps': ['Family Court'],
    'workers-rights': ['DIR', 'NVOSHA'],
    'human-rights': ['NERC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BME', 'State Bar'],
  },
  NH: {
    'family': ['Circuit Court - Family Division'],
    'small-claims': ['Circuit Court - Small Claims'],
    'employment': ['NHES', 'HRC', 'EEOC', 'Superior Court'],
    'housing': ['Circuit Court'],
    'criminal': ['Superior Court', 'Circuit Court'],
    'cps': ['Circuit Court - Family Division'],
    'workers-rights': ['DOL', 'OSHA'],
    'human-rights': ['HRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BMP', 'NHBA'],
  },
  NJ: {
    'family': ['Superior Court - Family Part'],
    'small-claims': ['Special Civil Part - Small Claims'],
    'employment': ['LWD', 'DCR', 'EEOC Newark', 'Superior Court'],
    'housing': ['Special Civil Part - Landlord Tenant'],
    'criminal': ['Superior Court - Criminal', 'Municipal Court'],
    'cps': ['Family Court'],
    'workers-rights': ['DWC', 'OSHA'],
    'human-rights': ['DCR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BME', 'State Bar'],
  },
  NM: {
    'family': ['District Court - Family'],
    'small-claims': ['Magistrate Court', 'Metropolitan Court'],
    'employment': ['DWS', 'HRD', 'EEOC Albuquerque', 'District Court'],
    'housing': ['Magistrate Court', 'Metropolitan Court'],
    'criminal': ['District Court', 'Magistrate Court'],
    'cps': ['Childrens Court'],
    'workers-rights': ['WCA', 'OSHA'],
    'human-rights': ['HRD', 'EEOC', 'Federal Court'],
    'agency-complaints': ['MBE', 'State Bar'],
  },
  NY: {
    'family': ['Supreme Court', 'Family Court'],
    'small-claims': ['Small Claims Court', 'Civil Court'],
    'employment': ['DOL', 'DHR', 'EEOC', 'Supreme Court'],
    'housing': ['Housing Court', 'Civil Court'],
    'criminal': ['Supreme Court', 'Criminal Court'],
    'cps': ['Family Court'],
    'workers-rights': ['WCB', 'OSHA'],
    'human-rights': ['DHR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['OPMC', 'State Bar', 'CCRB'],
  },
  NC: {
    'family': ['District Court - Family'],
    'small-claims': ['Small Claims - District Court'],
    'employment': ['DES', 'EEOC Charlotte', 'Superior Court'],
    'housing': ['Small Claims', 'District Court'],
    'criminal': ['Superior Court', 'District Court'],
    'cps': ['District Court - Juvenile'],
    'workers-rights': ['IC', 'NCDOL OSH'],
    'human-rights': ['EEOC', 'Federal Court'],
    'agency-complaints': ['NCMB', 'State Bar'],
  },
  ND: {
    'family': ['District Court'],
    'small-claims': ['Small Claims Court'],
    'employment': ['JSND', 'DHR', 'EEOC', 'District Court'],
    'housing': ['District Court'],
    'criminal': ['District Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['WSI', 'OSHA'],
    'human-rights': ['DHR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BME', 'SBAND'],
  },
  OH: {
    'family': ['Court of Common Pleas - Domestic Relations'],
    'small-claims': ['Small Claims - Municipal Court'],
    'employment': ['ODJFS', 'OCRC', 'EEOC Cleveland', 'Common Pleas'],
    'housing': ['Municipal Court'],
    'criminal': ['Common Pleas', 'Municipal Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['BWC', 'OSHA'],
    'human-rights': ['OCRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['SMBO', 'OSBA'],
  },
  OK: {
    'family': ['District Court - Family'],
    'small-claims': ['Small Claims - District Court'],
    'employment': ['OESC', 'EEOC Oklahoma City', 'District Court'],
    'housing': ['Small Claims', 'District Court'],
    'criminal': ['District Court'],
    'cps': ['Juvenile Division'],
    'workers-rights': ['WCC', 'OSHA'],
    'human-rights': ['EEOC', 'Federal Court'],
    'agency-complaints': ['OSBMLS', 'OBA'],
  },
  OR: {
    'family': ['Circuit Court - Family'],
    'small-claims': ['Small Claims - Circuit Court'],
    'employment': ['OED', 'BOLI', 'EEOC', 'Circuit Court'],
    'housing': ['Circuit Court'],
    'criminal': ['Circuit Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['WCB', 'OR-OSHA'],
    'human-rights': ['BOLI', 'EEOC', 'Federal Court'],
    'agency-complaints': ['OMB', 'OSB'],
  },
  PA: {
    'family': ['Court of Common Pleas - Family Division'],
    'small-claims': ['Magisterial District Court'],
    'employment': ['UC', 'PHRC', 'EEOC Philadelphia', 'Common Pleas'],
    'housing': ['Magisterial District Court', 'Municipal Court'],
    'criminal': ['Common Pleas', 'Municipal Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['WC', 'OSHA'],
    'human-rights': ['PHRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BPOA', 'PBA'],
  },
  RI: {
    'family': ['Family Court'],
    'small-claims': ['Small Claims - District Court'],
    'employment': ['DLT', 'RICHR', 'EEOC', 'Superior Court'],
    'housing': ['District Court'],
    'criminal': ['Superior Court', 'District Court'],
    'cps': ['Family Court'],
    'workers-rights': ['WCC', 'OSHA'],
    'human-rights': ['RICHR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['DOH', 'State Bar'],
  },
  SC: {
    'family': ['Family Court'],
    'small-claims': ['Magistrate Court'],
    'employment': ['DEW', 'SCHAC', 'EEOC', 'Circuit Court'],
    'housing': ['Magistrate Court'],
    'criminal': ['Circuit Court', 'General Sessions'],
    'cps': ['Family Court'],
    'workers-rights': ['WCC', 'OSHA'],
    'human-rights': ['SCHAC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['LLR', 'State Bar'],
  },
  SD: {
    'family': ['Circuit Court'],
    'small-claims': ['Small Claims Court'],
    'employment': ['DLR', 'EEOC', 'Circuit Court'],
    'housing': ['Circuit Court'],
    'criminal': ['Circuit Court'],
    'cps': ['Circuit Court - Juvenile'],
    'workers-rights': ['DLR', 'OSHA'],
    'human-rights': ['EEOC', 'Federal Court'],
    'agency-complaints': ['BMP', 'State Bar'],
  },
  TN: {
    'family': ['Circuit/Chancery Court'],
    'small-claims': ['General Sessions Court'],
    'employment': ['DOL', 'THRC', 'EEOC Nashville', 'Circuit Court'],
    'housing': ['General Sessions Court'],
    'criminal': ['Circuit/Criminal Court', 'General Sessions'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['BWC', 'TOSHA'],
    'human-rights': ['THRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['DOH', 'BPR'],
  },
  TX: {
    'family': ['District Court - Family', 'County Court at Law'],
    'small-claims': ['Justice Court', 'Small Claims Court'],
    'employment': ['TWC', 'EEOC', 'District Court'],
    'housing': ['Justice Court', 'County Court at Law'],
    'criminal': ['District Court', 'County Court'],
    'cps': ['District Court'],
    'workers-rights': ['TWC', 'TDI', 'OSHA'],
    'human-rights': ['THR', 'EEOC', 'Federal Court'],
    'agency-complaints': ['TSBME', 'State Bar', 'TCOLE'],
  },
  UT: {
    'family': ['District Court - Domestic'],
    'small-claims': ['Small Claims - District Court'],
    'employment': ['DWS', 'UALD', 'EEOC', 'District Court'],
    'housing': ['District Court'],
    'criminal': ['District Court', 'Justice Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['LCU', 'UOSH'],
    'human-rights': ['UALD', 'EEOC', 'Federal Court'],
    'agency-complaints': ['DOPL', 'State Bar'],
  },
  VT: {
    'family': ['Family Court'],
    'small-claims': ['Small Claims - Superior Court'],
    'employment': ['DOL', 'HRC', 'EEOC', 'Superior Court'],
    'housing': ['Superior Court'],
    'criminal': ['Superior Court'],
    'cps': ['Family Court'],
    'workers-rights': ['WC', 'VOSHA'],
    'human-rights': ['HRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BME', 'PRB'],
  },
  VA: {
    'family': ['Circuit Court', 'Juvenile and Domestic Relations'],
    'small-claims': ['General District Court'],
    'employment': ['VEC', 'EEOC', 'Circuit Court'],
    'housing': ['General District Court'],
    'criminal': ['Circuit Court', 'General District Court'],
    'cps': ['Juvenile and Domestic Relations Court'],
    'workers-rights': ['VWC', 'VOSH'],
    'human-rights': ['EEOC', 'Federal Court'],
    'agency-complaints': ['DHP', 'VSB'],
  },
  WA: {
    'family': ['Superior Court - Family'],
    'small-claims': ['Small Claims - District Court'],
    'employment': ['ESD', 'WSHRC', 'EEOC Seattle', 'Superior Court'],
    'housing': ['District Court', 'Superior Court'],
    'criminal': ['Superior Court', 'District Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['LNI', 'WISHA'],
    'human-rights': ['WSHRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['DOH', 'WSBA'],
  },
  WV: {
    'family': ['Family Court', 'Circuit Court'],
    'small-claims': ['Magistrate Court'],
    'employment': ['Workforce', 'WVHRC', 'EEOC', 'Circuit Court'],
    'housing': ['Magistrate Court'],
    'criminal': ['Circuit Court'],
    'cps': ['Circuit Court'],
    'workers-rights': ['IC', 'OSHA'],
    'human-rights': ['WVHRC', 'EEOC', 'Federal Court'],
    'agency-complaints': ['BOM', 'State Bar'],
  },
  WI: {
    'family': ['Circuit Court - Family'],
    'small-claims': ['Small Claims - Circuit Court'],
    'employment': ['DWD', 'ERD', 'EEOC Milwaukee', 'Circuit Court'],
    'housing': ['Small Claims', 'Circuit Court'],
    'criminal': ['Circuit Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['DWD', 'OSHA'],
    'human-rights': ['ERD', 'EEOC', 'Federal Court'],
    'agency-complaints': ['DSPS', 'State Bar'],
  },
  WY: {
    'family': ['District Court'],
    'small-claims': ['Circuit Court - Small Claims'],
    'employment': ['DOE', 'EEOC', 'District Court'],
    'housing': ['Circuit Court'],
    'criminal': ['District Court', 'Circuit Court'],
    'cps': ['Juvenile Court'],
    'workers-rights': ['WD', 'OSHA'],
    'human-rights': ['EEOC', 'Federal Court'],
    'agency-complaints': ['BM', 'State Bar'],
  },
};

// Generate SEO data for a funnel
const generateSEO = (state: string, legalArea: LegalCategory): FunnelConfig['seo'] => {
  const stateName = US_STATE_NAMES[state];
  const areaName = LEGAL_AREA_NAMES[legalArea];
  
  const seoTemplates: Record<LegalCategory, { title: string; description: string; keywords: string[]; h1: string }> = {
    'family': {
      title: `${stateName} Divorce & Family Law Self-Help | Free ${stateName} Forms`,
      description: `Navigate ${stateName} family court without an attorney. Get divorce forms, custody help, and step-by-step guidance for ${stateName} family law matters.`,
      keywords: [`${stateName} divorce`, `${stateName} family law`, `${stateName} custody`, `${stateName} divorce forms`, 'pro se divorce'],
      h1: `${stateName} Family Law Self-Help Center`,
    },
    'small-claims': {
      title: `${stateName} Small Claims Court Guide | File Without a Lawyer`,
      description: `Sue in ${stateName} small claims court without an attorney. Learn the process, filing fees, limits, and get the right forms for your case.`,
      keywords: [`${stateName} small claims`, `${stateName} small claims forms`, `${stateName} sue`, 'small claims limit'],
      h1: `${stateName} Small Claims Court Help`,
    },
    'employment': {
      title: `${stateName} Employment Law Help | Wrongful Termination & Wage Claims`,
      description: `File employment complaints in ${stateName}. Get help with wrongful termination, wage theft, discrimination, and workplace violations.`,
      keywords: [`${stateName} wrongful termination`, `${stateName} wage claim`, `${stateName} employment lawyer`, 'workplace discrimination'],
      h1: `${stateName} Employment Rights Self-Help`,
    },
    'housing': {
      title: `${stateName} Tenant Rights | Eviction Defense & Housing Help`,
      description: `Know your rights as a ${stateName} tenant. Get help with evictions, security deposits, repairs, and landlord disputes.`,
      keywords: [`${stateName} eviction`, `${stateName} tenant rights`, `${stateName} landlord`, 'security deposit'],
      h1: `${stateName} Housing & Tenant Rights Help`,
    },
    'criminal': {
      title: `${stateName} Criminal Defense Self-Help | Expungement & Record Sealing`,
      description: `Understand your rights in ${stateName} criminal court. Get help with expungement, record sealing, and criminal defense resources.`,
      keywords: [`${stateName} expungement`, `${stateName} criminal defense`, `${stateName} record sealing`, 'criminal record'],
      h1: `${stateName} Criminal Defense Resources`,
    },
    'cps': {
      title: `${stateName} CPS Defense | Child Welfare & Dependency Court Help`,
      description: `Navigate ${stateName} CPS investigations and dependency court. Get resources for parents facing child welfare proceedings.`,
      keywords: [`${stateName} CPS`, `${stateName} child welfare`, `${stateName} dependency court`, 'CPS investigation'],
      h1: `${stateName} CPS & Child Welfare Help`,
    },
    'workers-rights': {
      title: `${stateName} Workers Rights | OSHA & Workers Comp Help`,
      description: `File workers compensation claims and OSHA complaints in ${stateName}. Get help with workplace safety violations.`,
      keywords: [`${stateName} workers comp`, `${stateName} OSHA`, `${stateName} workplace injury`, 'workers compensation'],
      h1: `${stateName} Workers Rights & Safety`,
    },
    'human-rights': {
      title: `${stateName} Civil Rights | Discrimination Complaints & Help`,
      description: `File discrimination complaints in ${stateName}. Get help with civil rights violations, discrimination, and equality issues.`,
      keywords: [`${stateName} discrimination`, `${stateName} civil rights`, `${stateName} human rights`, 'discrimination complaint'],
      h1: `${stateName} Civil Rights Self-Help`,
    },
    'agency-complaints': {
      title: `${stateName} Agency Complaints | File Against Doctors, Police, Lawyers`,
      description: `File complaints against professionals in ${stateName}. Get help with medical board, bar association, and police complaints.`,
      keywords: [`${stateName} medical board complaint`, `${stateName} bar complaint`, `${stateName} police complaint`, 'professional misconduct'],
      h1: `${stateName} Professional Complaints Help`,
    },
    'personal-injury': {
      title: `${stateName} Personal Injury Self-Help | Accident Claims Guide`,
      description: `Navigate personal injury claims in ${stateName}. Get help with accident cases, medical bills, and injury compensation.`,
      keywords: [`${stateName} personal injury`, `${stateName} accident claim`, `${stateName} injury lawyer`, 'accident compensation'],
      h1: `${stateName} Personal Injury Resources`,
    },
    'immigration': {
      title: `${stateName} Immigration Help | Visa, Green Card & Citizenship`,
      description: `Get immigration help in ${stateName}. Navigate visa applications, green cards, and citizenship processes.`,
      keywords: [`${stateName} immigration`, `${stateName} green card`, `${stateName} visa`, 'immigration lawyer'],
      h1: `${stateName} Immigration Self-Help`,
    },
    'bankruptcy': {
      title: `${stateName} Bankruptcy Help | Chapter 7 & 13 Self-Filing`,
      description: `File bankruptcy in ${stateName} without an attorney. Get help with Chapter 7 and Chapter 13 bankruptcy forms.`,
      keywords: [`${stateName} bankruptcy`, `${stateName} chapter 7`, `${stateName} chapter 13`, 'bankruptcy lawyer'],
      h1: `${stateName} Bankruptcy Self-Help`,
    },
    'consumer-protection': {
      title: `${stateName} Consumer Protection | Fraud & Scam Complaints`,
      description: `File consumer complaints in ${stateName}. Get help with fraud, scams, and consumer protection issues.`,
      keywords: [`${stateName} consumer protection`, `${stateName} fraud`, `${stateName} scam`, 'consumer complaint'],
      h1: `${stateName} Consumer Protection Help`,
    },
  };

  return seoTemplates[legalArea];
};

// Generate all funnels for enabled states
export const generateUSFunnels = (): FunnelConfig[] => {
  const funnels: FunnelConfig[] = [];

  for (const state of ENABLED_STATES) {
    for (const legalArea of ALL_LEGAL_AREAS) {
      const funnelId = generateFunnelId('US', state, legalArea);
      const entryPoint = `/${generateSlug(state, legalArea)}`;
      
      funnels.push({
        id: funnelId,
        country: 'US',
        jurisdiction: state,
        legalArea,
        entryPoint,
        steps: STANDARD_STEPS,
        forms: STATE_FORMS[state]?.[legalArea] || [],
        courts: STATE_COURTS[state]?.[legalArea] || [],
        upsell: legalArea === 'criminal' ? 'one_time' : 'subscription',
        enabled: true,
        seo: generateSEO(state, legalArea),
      });
    }
  }

  return funnels;
};

// Pre-generated funnels
export const US_FUNNELS = generateUSFunnels();

// Get funnel by ID
export const getFunnelById = (id: string): FunnelConfig | undefined => {
  return US_FUNNELS.find(f => f.id === id);
};

// Get funnel by entry point
export const getFunnelByRoute = (route: string): FunnelConfig | undefined => {
  return US_FUNNELS.find(f => f.entryPoint === route);
};

// Get all funnels for a state
export const getFunnelsForState = (state: string): FunnelConfig[] => {
  return US_FUNNELS.filter(f => f.jurisdiction === state);
};

// Get all funnels for a legal area
export const getFunnelsForLegalArea = (legalArea: LegalCategory): FunnelConfig[] => {
  return US_FUNNELS.filter(f => f.legalArea === legalArea);
};

// Check if a state is enabled
export const isStateEnabled = (state: string): boolean => {
  return ENABLED_STATES.includes(state as typeof ENABLED_STATES[number]);
};

// Get all enabled entry routes
export const getAllEntryRoutes = (): string[] => {
  return US_FUNNELS.filter(f => f.enabled).map(f => f.entryPoint);
};

// Get state by abbreviation - returns full state name
export const getStateName = (abbreviation: string): string => {
  return US_STATE_NAMES[abbreviation] || abbreviation;
};
