import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function generateHash(content: string): string {
  let hash = 0;
  for (let i = 0; i < content.length; i++) {
    const char = content.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return Math.abs(hash).toString(16).padStart(8, "0").toUpperCase();
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
  );

  try {
    // Auth
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("Missing authorization");
    
    const anonClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? ""
    );
    const { data: { user }, error: authError } = await anonClient.auth.getUser(
      authHeader.replace("Bearer ", "")
    );
    if (authError || !user) throw new Error("Unauthorized");

    const { userId, caseId } = await req.json();
    if (userId !== user.id) throw new Error("Unauthorized");

    // Fetch enrollments with course info
    const { data: enrollments } = await supabase
      .from("course_enrollments")
      .select("*, courses(*)")
      .eq("user_id", user.id);

    // Fetch certificates
    const { data: certificates } = await supabase
      .from("course_certificates")
      .select("*")
      .eq("user_id", user.id);

    const now = new Date();
    const utcTimestamp = now.toISOString();
    const localTimestamp = now.toLocaleString("en-US", { timeZone: "America/New_York" });

    // Build PDF content as structured text (for server-side generation)
    const reportContent = {
      title: "Court Accountability Report",
      platform: "Generated by Justice Bot USA",
      generatedAt: {
        utc: utcTimestamp,
        local: `${localTimestamp} ET`,
      },
      caseId: caseId || "N/A",
      userId: user.id,
      enrollments: (enrollments || []).map((e: any) => ({
        courseTitle: e.courses?.title || "Unknown",
        provider: e.courses?.provider_name || "Unknown",
        acceptanceLabel: e.courses?.acceptance_label || "Unknown",
        status: e.status,
        enrolledAt: e.enrolled_at,
        completedAt: e.completed_at,
        hoursCompleted: e.hours_completed,
      })),
      certificates: (certificates || []).map((c: any) => ({
        courseTitle: c.course_title,
        provider: c.provider_name,
        hoursCompleted: c.hours_completed,
        completionDate: c.completion_date,
        certificateHash: c.certificate_hash,
        verificationLink: c.verification_link,
      })),
    };

    const contentString = JSON.stringify(reportContent);
    const documentHash = `JB-${generateHash(contentString)}`;

    // Log export (immutable audit)
    await supabase.from("court_export_logs").insert({
      user_id: user.id,
      case_id: caseId || null,
      export_type: "pdf",
      document_hash: documentHash,
      generation_timestamp_utc: utcTimestamp,
      generation_timestamp_local: localTimestamp,
      contents_summary: {
        enrollments_count: reportContent.enrollments.length,
        certificates_count: reportContent.certificates.length,
      },
    });

    // Return structured data for client to render
    // In production, this would generate a real PDF via a library
    return new Response(
      JSON.stringify({
        success: true,
        documentHash,
        generatedAt: utcTimestamp,
        report: reportContent,
      }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: error.message === "Unauthorized" ? 401 : 500,
      }
    );
  }
});
