-- Add columns to store comprehensive AI analysis results
ALTER TABLE case_merit_scores 
ADD COLUMN IF NOT EXISTS legal_pathway jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS required_forms jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS evidence_to_gather jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS filing_options jsonb DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS next_steps jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS improvement_suggestions jsonb DEFAULT '[]'::jsonb;

-- Add comment explaining the new fields
COMMENT ON COLUMN case_merit_scores.legal_pathway IS 'Step-by-step legal pathway generated by AI';
COMMENT ON COLUMN case_merit_scores.required_forms IS 'List of forms needed to file the case';
COMMENT ON COLUMN case_merit_scores.evidence_to_gather IS 'Evidence that should be collected';
COMMENT ON COLUMN case_merit_scores.filing_options IS 'Pro se vs attorney options with recommendations';
COMMENT ON COLUMN case_merit_scores.next_steps IS 'Immediate actionable next steps';
COMMENT ON COLUMN case_merit_scores.improvement_suggestions IS 'Suggestions to improve case merit score';