
INSERT INTO form_sources (jurisdiction_code, country, source_name, source_url, source_type, category, is_active) VALUES
('US-AL', 'US', 'Alabama Court Forms', 'https://www.alacourt.gov/CourtForms.aspx', 'court_website', 'general', true),
('US-AK', 'US', 'Alaska Court Forms', 'https://courts.alaska.gov/forms/index.htm', 'court_website', 'general', true),
('US-AZ', 'US', 'Arizona Court Forms', 'https://www.azcourts.gov/selfservicecenter/Self-Service-Forms', 'court_website', 'general', true),
('US-AR', 'US', 'Arkansas Court Forms', 'https://www.arcourts.gov/forms-and-publications', 'court_website', 'general', true),
('US-CO', 'US', 'Colorado Court Forms', 'https://www.courts.state.co.us/Forms/Index.cfm', 'court_website', 'general', true),
('US-CT', 'US', 'Connecticut Court Forms', 'https://www.jud.ct.gov/forms/', 'court_website', 'general', true),
('US-DE', 'US', 'Delaware Court Forms', 'https://courts.delaware.gov/forms/', 'court_website', 'general', true),
('US-DC', 'US', 'DC Superior Court Forms', 'https://www.dccourts.gov/services/forms', 'court_website', 'general', true),
('US-HI', 'US', 'Hawaii Court Forms', 'https://www.courts.state.hi.us/self-help/courts/forms', 'court_website', 'general', true),
('US-ID', 'US', 'Idaho Court Forms', 'https://www.isc.idaho.gov/forms', 'court_website', 'general', true),
('US-IN', 'US', 'Indiana Court Forms', 'https://www.in.gov/courts/selfservice/forms/', 'court_website', 'general', true),
('US-IA', 'US', 'Iowa Court Forms', 'https://www.iowacourts.gov/for-the-public/court-forms', 'court_website', 'general', true),
('US-KS', 'US', 'Kansas Court Forms', 'https://www.kscourts.org/Rules-Procedures-Forms/Forms', 'court_website', 'general', true),
('US-KY', 'US', 'Kentucky Court Forms', 'https://www.kycourts.gov/resources/legalforms/Pages/default.aspx', 'court_website', 'general', true),
('US-LA', 'US', 'Louisiana Court Forms', 'https://www.lasc.org/rules/supreme_court_forms', 'court_website', 'general', true),
('US-ME', 'US', 'Maine Court Forms', 'https://www.courts.maine.gov/fees_forms/forms/index.html', 'court_website', 'general', true),
('US-MD', 'US', 'Maryland Court Forms', 'https://www.courts.state.md.us/courtforms', 'court_website', 'general', true),
('US-MI', 'US', 'Michigan Court Forms', 'https://www.courts.michigan.gov/court-administration/admin-resources-by-topic/scao-approved-forms/', 'court_website', 'general', true),
('US-MN', 'US', 'Minnesota Court Forms', 'https://www.mncourts.gov/GetForms.aspx', 'court_website', 'general', true),
('US-MS', 'US', 'Mississippi Court Forms', 'https://courts.ms.gov/trialcourts/chancery/chanceryforms.php', 'court_website', 'general', true),
('US-MO', 'US', 'Missouri Court Forms', 'https://www.courts.mo.gov/page.jsp?id=267', 'court_website', 'general', true),
('US-MT', 'US', 'Montana Court Forms', 'https://courts.mt.gov/forms', 'court_website', 'general', true),
('US-NE', 'US', 'Nebraska Court Forms', 'https://supremecourt.nebraska.gov/self-help/court-forms', 'court_website', 'general', true),
('US-NV', 'US', 'Nevada Court Forms', 'https://selfhelp.nvcourts.gov/self-help/self-help-forms', 'court_website', 'general', true),
('US-NH', 'US', 'New Hampshire Court Forms', 'https://www.courts.nh.gov/forms', 'court_website', 'general', true),
('US-NM', 'US', 'New Mexico Court Forms', 'https://www.nmcourts.gov/forms.aspx', 'court_website', 'general', true),
('US-NC', 'US', 'North Carolina Court Forms', 'https://www.nccourts.gov/documents/forms', 'court_website', 'general', true),
('US-ND', 'US', 'North Dakota Court Forms', 'https://www.ndcourts.gov/legal-self-help/forms', 'court_website', 'general', true),
('US-OH', 'US', 'Ohio Court Forms', 'https://www.supremecourt.ohio.gov/JCS/CFC/DFCForms/', 'court_website', 'general', true),
('US-OK', 'US', 'Oklahoma Court Forms', 'https://www.oscn.net/forms/', 'court_website', 'general', true),
('US-OR', 'US', 'Oregon Court Forms', 'https://www.courts.oregon.gov/forms/Pages/default.aspx', 'court_website', 'general', true),
('US-RI', 'US', 'Rhode Island Court Forms', 'https://www.courts.ri.gov/PublicResources/forms/Pages/default.aspx', 'court_website', 'general', true),
('US-SC', 'US', 'South Carolina Court Forms', 'https://www.sccourts.org/forms/', 'court_website', 'general', true),
('US-SD', 'US', 'South Dakota Court Forms', 'https://ujs.sd.gov/Forms/', 'court_website', 'general', true),
('US-TN', 'US', 'Tennessee Court Forms', 'https://www.tncourts.gov/programs/self-help-center/forms', 'court_website', 'general', true),
('US-UT', 'US', 'Utah Court Forms', 'https://www.utcourts.gov/en/self-help/forms.html', 'court_website', 'general', true),
('US-VT', 'US', 'Vermont Court Forms', 'https://www.vermontjudiciary.org/self-help/court-forms', 'court_website', 'general', true),
('US-VA', 'US', 'Virginia Court Forms', 'https://www.vacourts.gov/forms/circuit.html', 'court_website', 'general', true),
('US-WV', 'US', 'West Virginia Court Forms', 'https://www.courtswv.gov/legal-community/court-rules/forms', 'court_website', 'general', true),
('US-WI', 'US', 'Wisconsin Court Forms', 'https://www.wicourts.gov/forms1/circuit.htm', 'court_website', 'general', true),
('US-WY', 'US', 'Wyoming Court Forms', 'https://www.courts.state.wy.us/court-rules/rules-and-forms/', 'court_website', 'general', true);
