
INSERT INTO form_sources (jurisdiction_code, country, source_name, source_url, source_type, category, is_active) VALUES
('US-FED', 'US', 'Justia Federal Forms', 'https://forms.justia.com/official-federal-forms/', 'legal_directory', 'general', true),
('US-AL', 'US', 'Justia Alabama Forms', 'https://forms.justia.com/alabama/', 'legal_directory', 'general', true),
('US-AK', 'US', 'Justia Alaska Forms', 'https://forms.justia.com/alaska/', 'legal_directory', 'general', true),
('US-AZ', 'US', 'Justia Arizona Forms', 'https://forms.justia.com/arizona/', 'legal_directory', 'general', true),
('US-AR', 'US', 'Justia Arkansas Forms', 'https://forms.justia.com/arkansas/', 'legal_directory', 'general', true),
('US-CA', 'US', 'Justia California Forms', 'https://forms.justia.com/california/', 'legal_directory', 'general', true),
('US-CO', 'US', 'Justia Colorado Forms', 'https://forms.justia.com/colorado/', 'legal_directory', 'general', true),
('US-CT', 'US', 'Justia Connecticut Forms', 'https://forms.justia.com/connecticut/', 'legal_directory', 'general', true),
('US-DE', 'US', 'Justia Delaware Forms', 'https://forms.justia.com/delaware/', 'legal_directory', 'general', true),
('US-DC', 'US', 'Justia DC Forms', 'https://forms.justia.com/district-of-columbia/', 'legal_directory', 'general', true),
('US-FL', 'US', 'Justia Florida Forms', 'https://forms.justia.com/florida/', 'legal_directory', 'general', true),
('US-GA', 'US', 'Justia Georgia Forms', 'https://forms.justia.com/georgia/', 'legal_directory', 'general', true),
('US-HI', 'US', 'Justia Hawaii Forms', 'https://forms.justia.com/hawaii/', 'legal_directory', 'general', true),
('US-ID', 'US', 'Justia Idaho Forms', 'https://forms.justia.com/idaho/', 'legal_directory', 'general', true),
('US-IL', 'US', 'Justia Illinois Forms', 'https://forms.justia.com/illinois/', 'legal_directory', 'general', true),
('US-IN', 'US', 'Justia Indiana Forms', 'https://forms.justia.com/indiana/', 'legal_directory', 'general', true),
('US-IA', 'US', 'Justia Iowa Forms', 'https://forms.justia.com/iowa/', 'legal_directory', 'general', true),
('US-KS', 'US', 'Justia Kansas Forms', 'https://forms.justia.com/kansas/', 'legal_directory', 'general', true),
('US-KY', 'US', 'Justia Kentucky Forms', 'https://forms.justia.com/kentucky/', 'legal_directory', 'general', true),
('US-LA', 'US', 'Justia Louisiana Forms', 'https://forms.justia.com/louisiana/', 'legal_directory', 'general', true),
('US-ME', 'US', 'Justia Maine Forms', 'https://forms.justia.com/maine/', 'legal_directory', 'general', true),
('US-MD', 'US', 'Justia Maryland Forms', 'https://forms.justia.com/maryland/', 'legal_directory', 'general', true),
('US-MA', 'US', 'Justia Massachusetts Forms', 'https://forms.justia.com/massachusetts/', 'legal_directory', 'general', true),
('US-MI', 'US', 'Justia Michigan Forms', 'https://forms.justia.com/michigan/', 'legal_directory', 'general', true),
('US-MN', 'US', 'Justia Minnesota Forms', 'https://forms.justia.com/minnesota/', 'legal_directory', 'general', true),
('US-MS', 'US', 'Justia Mississippi Forms', 'https://forms.justia.com/mississippi/', 'legal_directory', 'general', true),
('US-MO', 'US', 'Justia Missouri Forms', 'https://forms.justia.com/missouri/', 'legal_directory', 'general', true),
('US-MT', 'US', 'Justia Montana Forms', 'https://forms.justia.com/montana/', 'legal_directory', 'general', true),
('US-NE', 'US', 'Justia Nebraska Forms', 'https://forms.justia.com/nebraska/', 'legal_directory', 'general', true),
('US-NV', 'US', 'Justia Nevada Forms', 'https://forms.justia.com/nevada/', 'legal_directory', 'general', true),
('US-NH', 'US', 'Justia New Hampshire Forms', 'https://forms.justia.com/new-hampshire/', 'legal_directory', 'general', true),
('US-NJ', 'US', 'Justia New Jersey Forms', 'https://forms.justia.com/new-jersey/', 'legal_directory', 'general', true),
('US-NM', 'US', 'Justia New Mexico Forms', 'https://forms.justia.com/new-mexico/', 'legal_directory', 'general', true),
('US-NY', 'US', 'Justia New York Forms', 'https://forms.justia.com/new-york/', 'legal_directory', 'general', true),
('US-NC', 'US', 'Justia North Carolina Forms', 'https://forms.justia.com/north-carolina/', 'legal_directory', 'general', true),
('US-ND', 'US', 'Justia North Dakota Forms', 'https://forms.justia.com/north-dakota/', 'legal_directory', 'general', true),
('US-OH', 'US', 'Justia Ohio Forms', 'https://forms.justia.com/ohio/', 'legal_directory', 'general', true),
('US-OK', 'US', 'Justia Oklahoma Forms', 'https://forms.justia.com/oklahoma/', 'legal_directory', 'general', true),
('US-OR', 'US', 'Justia Oregon Forms', 'https://forms.justia.com/oregon/', 'legal_directory', 'general', true),
('US-PA', 'US', 'Justia Pennsylvania Forms', 'https://forms.justia.com/pennsylvania/', 'legal_directory', 'general', true),
('US-RI', 'US', 'Justia Rhode Island Forms', 'https://forms.justia.com/rhode-island/', 'legal_directory', 'general', true),
('US-SC', 'US', 'Justia South Carolina Forms', 'https://forms.justia.com/south-carolina/', 'legal_directory', 'general', true),
('US-SD', 'US', 'Justia South Dakota Forms', 'https://forms.justia.com/south-dakota/', 'legal_directory', 'general', true),
('US-TN', 'US', 'Justia Tennessee Forms', 'https://forms.justia.com/tennessee/', 'legal_directory', 'general', true),
('US-TX', 'US', 'Justia Texas Forms', 'https://forms.justia.com/texas/', 'legal_directory', 'general', true),
('US-UT', 'US', 'Justia Utah Forms', 'https://forms.justia.com/utah/', 'legal_directory', 'general', true),
('US-VT', 'US', 'Justia Vermont Forms', 'https://forms.justia.com/vermont/', 'legal_directory', 'general', true),
('US-VA', 'US', 'Justia Virginia Forms', 'https://forms.justia.com/virginia/', 'legal_directory', 'general', true),
('US-WA', 'US', 'Justia Washington Forms', 'https://forms.justia.com/washington/', 'legal_directory', 'general', true),
('US-WV', 'US', 'Justia West Virginia Forms', 'https://forms.justia.com/west-virginia/', 'legal_directory', 'general', true),
('US-WI', 'US', 'Justia Wisconsin Forms', 'https://forms.justia.com/wisconsin/', 'legal_directory', 'general', true),
('US-WY', 'US', 'Justia Wyoming Forms', 'https://forms.justia.com/wyoming/', 'legal_directory', 'general', true);
