-- Create job_status enum if not exists
DO $$ BEGIN
  CREATE TYPE job_status AS ENUM ('queued', 'running', 'done', 'error');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Jobs table (cron worker claims these)
CREATE TABLE IF NOT EXISTS public.jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text NOT NULL,
  status job_status NOT NULL DEFAULT 'queued',
  payload jsonb NOT NULL,
  error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  completed_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_jobs_status ON public.jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_type_status ON public.jobs(type, status);

-- Enable RLS on jobs (backend-only writes via service role)
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- Service role can do everything on jobs
CREATE POLICY "Service role full access on jobs"
ON public.jobs FOR ALL
USING (true)
WITH CHECK (true);

-- Add INSERT policy for case_sweeps for service role
CREATE POLICY "Service role can insert case sweeps"
ON public.case_sweeps FOR INSERT
WITH CHECK (true);

-- Add UPDATE policy for case_sweeps for service role  
CREATE POLICY "Service role can update case sweeps"
ON public.case_sweeps FOR UPDATE
USING (true)
WITH CHECK (true);

-- Ensure case_merit_scores has proper service role access
CREATE POLICY "Service role can insert merit scores"
ON public.case_merit_scores FOR INSERT
WITH CHECK (true);

CREATE POLICY "Service role can update merit scores"
ON public.case_merit_scores FOR UPDATE
USING (true)
WITH CHECK (true);