// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhgkshjqgagxfllgvhco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZ2tzaGpxZ2FneGZsbGd2aGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMTM0NjAsImV4cCI6MjA3NDY4OTQ2MH0.v-w_WlZnzX690On8tBZB7pQCZ6i-I6jR6gtbtL-25cM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});